In [0]:
NAME = "Daniel Martin"
COLLABORATORS = ""

---

# Lab 6a: Skip Gram

**Please read the following instructions very carefully**

## Working on the assignment / FAQs
- **Always use the seed/random_state as *42* wherever applicable** (This is to ensure repeatability in answers, across students and coding environments) 
- The type of question and the points they carry are indicated in each question cell
- To avoid any ambiguity, each question also specifies what *value* must be set. Note that these are dummy values and not the answers
- If an autograded question has multiple answers (due to differences in handling NaNs, zeros etc.), all answers will be considered.
- You can delete the `raise NotImplementedError()`
- **Submitting the assignment** : Download the '.ipynb' file from Colab and upload it to bcourses. Do not delete any outputs from cells before submitting.
- That's about it. Happy coding!


Available software:
 - Python's Gensim module: https://radimrehurek.com/gensim/ (install using pip)
 - Sklearn’s  TSNE module in case you use TSNE to reduce dimension (optional)
 - Python’s Matplotlib (optional)

_Note: The most important hyper parameters of skip-gram/CBOW are vector size and windows size_


In [3]:
!pip install gensim
!wget -nc https://s3.amazonaws.com/dl4j-distribution/GoogleNews-vectors-negative300.bin.gz 


import pandas as pd
import numpy as np 
import gensim
from sklearn.cluster import KMeans

File ‘GoogleNews-vectors-negative300.bin.gz’ already there; not retrieving.



In [4]:
from gensim.models import KeyedVectors
model = KeyedVectors.load_word2vec_format('GoogleNews-vectors-negative300.bin.gz', binary=True)

/usr/local/lib/python3.6/dist-packages/smart_open/smart_open_lib.py:398: UserWarning: This function is deprecated, use smart_open.open instead. See the migration notes for details: https://github.com/RaRe-Technologies/smart_open/blob/master/README.rst#migrating-to-the-new-open-function
  'See the migration notes for details: %s' % _MIGRATION_NOTES_URL


**Q1 (1 point)** : Find the cosine similarity between the following word pairs

- (France, England)
- (smaller, bigger)
- (England, London)
- (France, Rocket)
- (big, bigger)

In [5]:
#Replace 0 with the code / value; Do not delete this cell
similarity_pair1 = model.similarity('France','England')
similarity_pair2 = model.similarity('smaller','bigger')
similarity_pair3 = model.similarity('England','London')
similarity_pair4 = model.similarity('France','Rocket')
similarity_pair5 = model.similarity('big','bigger')



/usr/local/lib/python3.6/dist-packages/gensim/matutils.py:737: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if np.issubdtype(vec.dtype, np.int):


In [6]:
#This is an autograded cell, do not edit/delete
print(similarity_pair1, similarity_pair2, similarity_pair3, similarity_pair4, similarity_pair5)

0.39804944 0.7302272 0.43992856 0.07114174 0.68423855


**Q2 (1 point)** : Write an expression to extract the vector representations of the words: 

- France
- England
- smaller
- bigger
- rocket
- big

Get only the first 5 elements for each vector representation.

In [0]:
#Replace 0 with the code / value to get the first 5 elements of each vector; Do not delete this cell
vector_1 = model['France'][:5]
vector_2 = model['England'][:5]
vector_3 = model['smaller'][:5]
vector_4 = model['bigger'][:5]
vector_5 = model['rocket'][:5]
vector_6 = model['big'][:5]



In [8]:
#This is an autograded cell, do not edit/delete
print(vector_1)
print(vector_2)
print(vector_3)
print(vector_4)
print(vector_5)
print(vector_6)


[0.04858398 0.07861328 0.32421875 0.03491211 0.07714844]
[-0.19824219  0.11523438  0.0625     -0.05834961  0.2265625 ]
[-0.05004883  0.03417969 -0.0703125   0.17578125  0.00689697]
[-0.06542969 -0.09521484 -0.06225586  0.16210938  0.01989746]
[-0.03198242  0.27148438 -0.2890625  -0.15429688  0.16894531]
[ 0.11132812  0.10595703 -0.07373047  0.18847656  0.07666016]


**Q3 (1 point)**: Find the euclidean distances between the word pairs : 

- (France, England)
- (smaller, bigger)
- (England, London)
- (France, Rocket)
- (big, bigger)


In [0]:
#Replace 0 with the code / value; Do not delete this cell
eu_dist1 = np.linalg.norm(model['France']-model['England'])
eu_dist2 = np.linalg.norm(model['smaller']-model['bigger'])
eu_dist3 = np.linalg.norm(model['England']-model['London'])
eu_dist4 = np.linalg.norm(model['France']-model['Rocket'])
eu_dist5 = np.linalg.norm(model['big']-model['bigger'])



In [10]:
#This is an autograded cell, do not edit / delete
print(eu_dist1)
print(eu_dist2)
print(eu_dist3)
print(eu_dist4)
print(eu_dist5)


3.0151067
1.8618743
2.8752837
3.892071
1.9586496


**Q4 (2 points)**: What is the relationship between the magnitude of individual vectors, the vectors themselves and the cosine distance for any pair of words. Use any tuple in Q1 as an example to support your answer.

**Do not delete the below cell**

In [0]:
# ex) (France, England)
# cosine similarity cos(a,b) = a(dot product)b / sqrt(a(dot product)a) * sqrt(b(dot product)b)
# cos(France, England) = France_vec * England_vec / (sqrt(Franc_vec*France_vec))*(sqrt(England_vec*England_vec))


**Q5 (1 point)**: Time to dabble with the power of Word2Vec. Find the 2 closest words  for the following conditions:  
- (King - Man + Queen)
- (bigger - big + small)
- (man + programmer - woman)
- (waiting - wait + run)
- (Texas + Milwaukee – Wisconsin)

In [11]:
#Replace 0 with the code / value; Do not delete this cell
closest1 = model.most_similar(positive=['King','Queen'], negative=['Man'])[:2]
closest2 = model.most_similar(positive=['bigger','small'], negative=['big'])[:2]
closest3 = model.most_similar(positive=['man','programmer'], negative=['woman'])[:2]
closest4 = model.most_similar(positive=['waiting','run'], negative=['wait'])[:2]
closest5 = model.most_similar(positive=['Texas','Milwaukee'], negative=['Wisconsin'])[:2]


/usr/local/lib/python3.6/dist-packages/gensim/matutils.py:737: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if np.issubdtype(vec.dtype, np.int):


In [12]:
#This is an autograded cell, do not edit/delete
print(closest1)
print(closest2)
print(closest3)
print(closest4)
print(closest5)


[('Queen_Elizabeth', 0.5257916450500488), ('monarch', 0.5004087090492249)]
[('larger', 0.7402471899986267), ('smaller', 0.732999324798584)]
[('programer', 0.5371963977813721), ('programmers', 0.5310999155044556)]
[('running', 0.5654535889625549), ('runs', 0.49640005826950073)]
[('Houston', 0.7767744064331055), ('Fort_Worth', 0.7270511388778687)]


**Q6 (3 points)**: Using the vectors for the words in the Google News dataset, explore the semantic representation of these words through K-means clustering and explain your findings.

*Note : Since there are ~3Mil words in the vocabulary, you can downsample it to ~20-30k randomly selected words*

**Do not delete the below cell**

In [13]:
from random import sample
import numpy as np

words = list(model.wv.vocab.keys())
sample = sample(words, 20000)
#sample

X = np.empty((20000, 300))
for i in range(20000):
  X[i] = model[sample[i]]

X.shape

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
  after removing the cwd from sys.path.


(20000, 300)

In [14]:
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

for k in range(2,9):
  kmeans = KMeans(n_clusters = k, random_state = 42)
  kmeans.fit(X)
  score = silhouette_score(X, kmeans.labels_)
  print('k: {} score: {}'.format(k, score)) 


k: 2 score: 0.2153115242061107
k: 3 score: 0.1291362212919472
k: 4 score: 0.07297147856266706
k: 5 score: 0.06197115288921009
k: 6 score: 0.05694870119466965
k: 7 score: 0.04609936400448944
k: 8 score: 0.03132558666142625


In [19]:
# 2 is best K
kmeans = KMeans(n_clusters = 2, random_state = 42)
kmeans.fit(X)

cluster_1 = model.similar_by_vector(kmeans.cluster_centers_[0])[:5]
cluster_2 = model.similar_by_vector(kmeans.cluster_centers_[1])[:5]
print(cluster_1)
print(cluster_2)

# The first cluster is a cluster of words that appears to names or authors from
# Google's news data.  This could be why those words and their semantic representation
# are clustered together.  The second cluster seems to by words that in HTML or 
# irregular .net syntax.  However, I do feel that these clusters may overlap 
# (not a clean cluster), especially since there are so many data points and the 
# best K was 2. 

/usr/local/lib/python3.6/dist-packages/gensim/matutils.py:737: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if np.issubdtype(vec.dtype, np.int):


[('Emil_Protalinski_Published', 0.9194611310958862), ('By_QianMian_####-##-##', 0.917617678642273), ('By_HuDie_####-##-##', 0.9174624681472778), ('By_XiaoBing_####-##-##', 0.9159759283065796), ('BY_GEOFF_KOHL', 0.9159120917320251)]
[('http_dol##.net_index###.html_http', 0.918448805809021), ('dol##.net_index####.html_http_dol##.net', 0.9081463813781738), ('index###.html_http_dol##.net_index###.html', 0.9070696830749512), ('Deltagen_undertakes', 0.9042704105377197), ('By_TRICIA_SCRUGGS', 0.9025315046310425)]


**Q7 (1 point)**: What loss function does the skipgram model use and briefly describe what this function is minimizing.

**Do not delete the below cell**

In [0]:
# Skipgram model uses categorical cross-entropy loss function.
# Categorical cross-entropy is used for single label categorization, when only 
# one category is applicable for each data point. This loss function is minimizing
# the difference (error) between the true distribution class (usually one-hot encoded) 
# and the distribution of the predictions.  Minimizing the dot product, if normalized
# using softmax, of the predicted vector and the true vector.


**Bonus Question (1 point)** : Find at least 2 interesting word vec combinations like the ones given in Q5

**Do not delete the below cell**

In [21]:
inter_one = model.most_similar(positive=['Porsche','BMW'], negative=['Mercedes'])[:2]
inter_two = model.most_similar(positive=['California','New_York'], negative=['Nebraska'])[:2]

/usr/local/lib/python3.6/dist-packages/gensim/matutils.py:737: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if np.issubdtype(vec.dtype, np.int):


In [22]:
print(inter_one)
print(inter_two)

[('Audi', 0.6969912052154541), ('Volkswagen', 0.6102272868156433)]
[('Los_Angeles', 0.6218940019607544), ('San_Francisco', 0.5677804946899414)]
